### ISSUE TITLE
config: cannot disable auto linking for Android without disabling it for iOS aswell

### ISSUE THREAD

**Issue by blu3beri** [react-native-community/cli#1584]
## Environment

```sh
npx react-native info
```
```yaml
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 3.15 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.config/noot/using/node
    Yarn: 1.22.17 - ~/.config/noot/using/yarn
    npm: 8.5.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

I control a library with some native code using turbo modules. I fixed auto linking for iOS in this library but I did not get it working for Android. I would like to disable Autolinking for android only and keep iOS enabled. I checked the docs and it says I have to add this to my library:

```js
// react-native.config.js
module.exports = {
  dependency: {
    platforms: {
      android: null, // disable Android platform, other platforms will still autolink if provided
    },
  },
};
```

And I believe that here [schema.ts](https://github.com/react-native-community/cli/blob/e044e7b0f93afec2b7e0e0d98cc994c02a4df1e1/packages/cli-config/src/schema.ts#L76) the schema does not allow for `null`. Which is incompatible then with the example. Keeping it like `android: {}` will result in it being filled with the default values again. Also, adding all the default values with an empty string also results in an invalid configuration.

## Reproducible Demo

1. Create a react native library. 
2. Execute the following command
```sh
cat <<EOF >> react-native.config.js
module.exports = {
  dependency: {
    platforms: {
      android: null,
    },
  },
};
EOF
```
3. add the library to your project
4. Execute the following command:
```sh
react-native config
# or 
react-native config | jq ".dependencies"
```

And it should show that the `dependencies` object is empty.

<hr>

I am not an expert with Autolinking and the whole process around it. Maybe I interpreted something wrong and please correct me if I made a simple mistake somewhere.

possibly related PR: #1297
